"""
report_generator.py — PDF report generator

Generates structured investigative reports from verified data.

IMPORTANT:
- All report content comes from verified database records and analytics.
- AI-generated narrative is clearly marked as AI-generated.
- Bank notices are clearly marked as "TEMPLATE REQUIRING AUTHORIZED REVIEW".
- This system does NOT produce legally valid court documents without human review.

STATUS: IMPLEMENTED
"""
import logging
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any

from fpdf import FPDF

from backend.config import REPORT_OUTPUT_DIR
from backend.models.schemas import InvestigationResponse

logger = logging.getLogger(__name__)

REPORT_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def _clean_text(s: str) -> str:
    """Clean text for standard PDF Latin-1 encoding."""
    if not s:
        return ""
    replacements = {
        "—": "--",
        "–": "-",
        "₹": "Rs. ",
        "⚠": "[!]",
        "•": "*",
        "“": '"',
        "”": '"',
        "‘": "'",
        "’": "'",
    }
    for orig, repl in replacements.items():
        s = s.replace(orig, repl)
    return s.encode("latin-1", errors="replace").decode("latin-1")


class InvestigationReport(FPDF):
    """Custom FPDF subclass for the investigation report."""

    def header(self):
        self.set_font("Helvetica", "B", 12)
        self.cell(0, 8, _clean_text("OPERATION ABHEDYA-CHAKRA -- Freeze-First Investigation Report"), align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 6, _clean_text("PROTOTYPE -- Decision Support Tool -- NOT a legal document -- Requires authorized human review"), align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, _clean_text(f"Page {self.page_no()} | DEVELOPMENT / SYNTHETIC DATA | Abhedya-Chakra v1.0"), align="C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 11)
        self.set_fill_color(30, 30, 80)
        self.set_text_color(255, 255, 255)
        self.cell(0, 8, _clean_text(f"  {title}"), fill=True, new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)
        self.ln(2)

    def body_text(self, text: str):
        self.set_font("Helvetica", "", 9)
        self.multi_cell(0, 5, _clean_text(text))
        self.ln(1)

    def kv_row(self, key: str, value: str):
        self.set_font("Helvetica", "B", 9)
        self.cell(55, 6, _clean_text(key + ":"), new_x="RIGHT", new_y="LAST")
        self.set_font("Helvetica", "", 9)
        self.multi_cell(0, 6, _clean_text(str(value)), new_x="LMARGIN", new_y="NEXT")

    def warning_box(self, text: str):
        self.set_fill_color(255, 243, 200)
        self.set_font("Helvetica", "I", 8)
        self.multi_cell(0, 5, _clean_text(f"[!] {text}"), fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)


def generate_pdf_report(
    investigation: InvestigationResponse,
    ai_narrative: str = "",
    output_path: Path | None = None,
) -> Path:
    """
    Generate a PDF investigation report from verified data.

    Args:
        investigation: Full investigation response
        ai_narrative: Optional AI-generated narrative (clearly marked)
        output_path: Where to save the PDF

    Returns:
        Path to the saved PDF file
    """
    if output_path is None:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_path = REPORT_OUTPUT_DIR / f"report_{investigation.victim_account}_{ts}.pdf"

    pdf = InvestigationReport()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # ── Section 1: Case Information ─────────────────────────────────────
    pdf.section_title("1. CASE INFORMATION")
    pdf.kv_row("Victim Account", investigation.victim_account)
    pdf.kv_row("Investigated At", investigation.investigated_at)
    pdf.kv_row("Data Label", investigation.data_label)
    pdf.warning_box(
        "This report is generated by an automated decision-support prototype. "
        "All findings require verification by authorized investigators. "
        "Risk scores are analytical signals, not legal conclusions."
    )

    # ── Section 2: Account Summary ──────────────────────────────────────
    pdf.section_title("2. VICTIM ACCOUNT SUMMARY")
    acc = investigation.account
    pdf.kv_row("Account ID", acc.account_id)
    pdf.kv_row("Total Received", f"Rs. {acc.total_received:,.2f}")
    pdf.kv_row("Total Sent", f"Rs. {acc.total_sent:,.2f}")
    pdf.kv_row("Net Balance", f"Rs. {acc.net_balance:,.2f}")
    pdf.kv_row("Transactions", str(acc.transaction_count))
    pdf.kv_row("First Seen", str(acc.first_seen))
    pdf.kv_row("Last Seen", str(acc.last_seen))
    pdf.kv_row("Banks", ", ".join(acc.banks))

    # ── Section 3: Risk Analysis ─────────────────────────────────────────
    pdf.section_title("3. RISK ANALYSIS")
    risk = investigation.risk
    pdf.kv_row("Risk Score", f"{risk.score}/100 ({risk.label})")
    pdf.kv_row("Disclaimer", risk.disclaimer)
    if risk.reasons:
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(0, 6, "Triggered Signals:", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        for r in risk.reasons:
            pdf.cell(0, 5, _clean_text(f"  [{r.weight:2d}pt] {r.code}: {r.detail}"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # ── Section 4: Tainted Balance ───────────────────────────────────────
    pdf.section_title("4. TAINTED BALANCE (Proportional Model)")
    taint = investigation.taint
    pdf.kv_row("Account", taint.account_id)
    pdf.kv_row("Tainted Amount", f"Rs. {taint.tainted_amount:,.2f}")
    pdf.kv_row("Total Balance", f"Rs. {taint.total_balance:,.2f}")
    pdf.kv_row("Taint Ratio", f"{taint.taint_ratio:.1%}")
    pdf.kv_row("Model", taint.model_used)
    pdf.warning_box(taint.disclaimer)

    # ── Section 5: Freeze Priority ───────────────────────────────────────
    pdf.section_title("5. FREEZE PRIORITY PLAN")
    freeze = investigation.freeze_plan
    pdf.kv_row("Method", freeze.method)
    pdf.kv_row("Total Estimated Recoverable", f"Rs. {freeze.total_estimated_recoverable:,.2f}")
    pdf.warning_box(freeze.disclaimer)

    pdf.set_font("Helvetica", "B", 9)
    col_widths = [12, 35, 20, 15, 30, 30, 25]
    headers = ["Rank", "Account", "Bank", "Layer", "Tainted (Rs.)", "Blocked (Rs.)", "Risk"]
    for i, h in enumerate(headers):
        pdf.cell(col_widths[i], 6, _clean_text(h), border=1)
    pdf.ln()
    pdf.set_font("Helvetica", "", 8)
    for c in freeze.freeze_candidates:
        row = [
            str(c.rank),
            c.account_id[:18],
            c.bank[:8],
            str(c.layer),
            f"{c.tainted_amount_held:,.0f}",
            f"{c.estimated_blocked_amount:,.0f}",
            str(c.risk_score or "N/A"),
        ]
        for i, val in enumerate(row):
            pdf.cell(col_widths[i], 5, _clean_text(val), border=1)
        pdf.ln()
    pdf.ln(3)

    # ── Section 6: Timeline ──────────────────────────────────────────────
    pdf.section_title("6. TRANSACTION TIMELINE (verified data only)")
    pdf.set_font("Helvetica", "", 8)
    for event in investigation.timeline:
        pdf.cell(0, 5, _clean_text(f"{event.timestamp}  {event.description}"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # ── Section 7: Evidence Summary ──────────────────────────────────────
    pdf.section_title("7. EVIDENCE SUMMARY")
    tx_evidence = [e for e in investigation.evidence if e.evidence_type == "transaction"]
    pdf.kv_row("Transaction evidence items", str(len(tx_evidence)))
    pdf.kv_row("Total evidence items", str(len(investigation.evidence)))
    pdf.body_text(
        "Full transaction-level evidence is available via the /api/evidence/ endpoint. "
        "Each item is traceable to a specific database record."
    )

    # ── Section 8: Bank-wise Actions ────────────────────────────────────
    pdf.section_title("8. BANK-WISE ACTION SUMMARY")
    # Group freeze candidates by bank
    banks_map: Dict[str, list] = {}
    for c in freeze.freeze_candidates:
        banks_map.setdefault(c.bank, []).append(c)

    for bank, candidates in banks_map.items():
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(0, 6, _clean_text(f"Bank: {bank}"), new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        for c in candidates:
            pdf.cell(0, 5, _clean_text(f"  Account: {c.account_id} | IFSC: {c.ifsc or 'N/A'} | Tainted: Rs.{c.tainted_amount_held:,.0f}"), new_x="LMARGIN", new_y="NEXT")
        pdf.warning_box(
            f"The above is a TEMPLATE NOTICE for bank {bank}. "
            "Must be reviewed and authorized before dispatch per Sec. 91 CrPC / BNSS."
        )

    # ── Section 9: AI Narrative (if available) ──────────────────────────
    if ai_narrative and ai_narrative.strip():
        pdf.section_title("9. AI-GENERATED NARRATIVE (Ollama)")
        pdf.warning_box(
            "The following narrative was generated by a local AI model (Ollama). "
            "It is based on structured verified facts only. Raw narration was excluded. "
            "The AI has been instructed not to declare guilt or innocence. "
            "This narrative requires human verification before any official use."
        )
        pdf.body_text(ai_narrative)

    pdf.output(str(output_path))
    logger.info(f"PDF report generated: {output_path}")
    return output_path
